name: Deploy Feed

on:
  schedule:
    - cron:  '0 6,18 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/cache/restore@v3
        id: restore-cache
        with:
          path: feed
          key: feed
      - run: curl -o techblog-original.xml https://yamadashy.github.io/tech-blog-rss-feed/feeds/rss.xml
      - run: curl -o classmethod-original.xml https://dev.classmethod.jp/feed/
      - run: curl -o zenn-original.xml https://zenn.dev/feed
      - run: curl -o qiita-original.xml https://qiita.com/popular-items/feed
      - run: npx xslt3 -xsl:qiita.xsl -s:qiita-original.xml -o:qiita-norm.xml
      - name: Filter techblog
        uses: bishishin/filter-feed-by-likes-action@main
        with:
          original: techblog-original.xml
          cache: feed/techblog.xml
          output: techblog.xml
          threshold: ${{ vars.LIKE_THRESHOLD_COMPANY }}
      - name: Filter classmethod
        uses: bishishin/filter-feed-by-likes-action@v0
        with:
          original: classmethod-original.xml
          cache: feed/classmethod.xml
          output: classmethod.xml
          threshold: ${{ vars.LIKE_THRESHOLD_COMPANY }}
      - name: Filter zenn
        uses: bishishin/filter-feed-by-likes-action@v0.1.0
        with:
          original: zenn-original.xml
          cache: feed/zenn.xml
          output: zenn.xml
          threshold: ${{ vars.LIKE_THRESHOLD_COMMUNITY }}  # zennやqiitaには独自のいいね機能があり、はてブの利用率が低いと思われるため、閾値を別にする
      - name: Filter qiita
        uses: bishishin/filter-feed-by-likes-action@1832159cd8cbf02517373e306f4ed8111a9fa4e0
        with:
          original: qiita-norm.xml
          cache: feed/qiita.xml
          output: qiita.xml
          threshold: ${{ vars.LIKE_THRESHOLD_COMMUNITY }}
      - run: npx xslt3 -xsl:expired.xsl -s:techblog.xml -o:feed/techblog.xml limitDateTime="$(date +%Y-%m-%dT%H:%M:%SZ -u -d '14 days ago')"
      - run: npx xslt3 -xsl:expired.xsl -s:classmethod.xml -o:feed/classmethod.xml limitDateTime="$(date +%Y-%m-%dT%H:%M:%SZ -u -d '14 days ago')"
      - run: npx xslt3 -xsl:expired.xsl -s:zenn.xml -o:feed/zenn.xml limitDateTime="$(date +%Y-%m-%dT%H:%M:%SZ -u -d '14 days ago')"
      - run: npx xslt3 -xsl:expired.xsl -s:qiita.xml -o:feed/qiita.xml limitDateTime="$(date +%Y-%m-%dT%H:%M:%SZ -u -d '14 days ago')"
      - uses: actions/cache/save@v3
        id: save-cache
        with:
          path: feed
          key: feed-${{ github.run_id }}
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'feed'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
